package com.company.core.managers;

import org.springframework.stereotype.Component;

import com.company.core.managers.base.CoGenericAbstractManager;
import com.company.core.model.CoDataInputGroup;
import com.company.core.model.CoDataInputGroupPK;
import com.company.core.repositories.CoDataInputGroupRepository;

/**
* Generated by Spring Data Generator on 02/07/2018
*/
@Component
public class CoDataInputGroupManager extends CoGenericAbstractManager<CoDataInputGroup, CoDataInputGroupPK, CoDataInputGroupRepository> {

	public CoDataInputGroupManager(CoDataInputGroupRepository repo) {
		super(repo);
		// TODO Auto-generated constructor stub
	}

}
