package com.company.core.managers;

import org.springframework.data.rest.core.annotation.RestResource;
import org.springframework.stereotype.Component;

import com.company.core.managers.base.CoGenericAbstractManager;
import com.company.core.model.CoData;
import com.company.core.repositories.CoDataRepository;

/**
* Generated by Spring Data Generator on 02/07/2018
*/
@Component
public class CoDataManager extends CoGenericAbstractManager<CoData, Integer, CoDataRepository> {

    public CoDataManager(CoDataRepository repo) {
		super(repo);
		// TODO Auto-generated constructor stub
	}
    
}
