package com.company.core.repositories;

import com.company.core.model.CoDataInputGroup;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;
import com.company.core.model.CoDataInputGroupPK;

/**
* Generated by Spring Data Generator on 02/07/2018
*/
@Repository
public interface CoDataInputGroupRepository extends JpaRepository<CoDataInputGroup, CoDataInputGroupPK>, JpaSpecificationExecutor<CoDataInputGroup> {

}
